INSERT IGNORE INTO currencies (code, name, symbol, is_default) VALUES
('AED', 'UAE Dirham', 'AED', 0),
('AUD', 'Australian Dollar', '$', 0),
('BGN', 'Bulgarian Lev', 'BGN', 0),
('BRL', 'Brazilian Real', 'R$', 0),
('CAD', 'Canadian Dollar', '$', 0),
('CHF', 'Swiss Franc', 'CHF', 0),
('CLP', 'Chilean Peso', '$', 0),
('CNY', 'Chinese Yuan', 'CNY', 0),
('COP', 'Colombian Peso', '$', 0),
('CZK', 'Czech Koruna', 'CZK', 0),
('DKK', 'Danish Krone', 'DKK', 0),
('EUR', 'Euro', 'EUR', 0),
('GBP', 'British Pound', 'GBP', 0),
('GHS', 'Ghanaian Cedi', 'GHS', 0),
('HKD', 'Hong Kong Dollar', '$', 0),
('HUF', 'Hungarian Forint', 'HUF', 0),
('IDR', 'Indonesian Rupiah', 'Rp', 0),
('ILS', 'Israeli New Shekel', 'ILS', 0),
('INR', 'Indian Rupee', 'INR', 0),
('JPY', 'Japanese Yen', 'JPY', 0),
('KES', 'Kenyan Shilling', 'KES', 0),
('KRW', 'South Korean Won', 'KRW', 0),
('KWD', 'Kuwaiti Dinar', 'KWD', 0),
('MAD', 'Moroccan Dirham', 'MAD', 0),
('MXN', 'Mexican Peso', '$', 0),
('MYR', 'Malaysian Ringgit', 'MYR', 0),
('NGN', 'Nigerian Naira', 'NGN', 0),
('NOK', 'Norwegian Krone', 'NOK', 0),
('NZD', 'New Zealand Dollar', '$', 0),
('PEN', 'Peruvian Sol', 'PEN', 0),
('PHP', 'Philippine Peso', 'PHP', 0),
('PLN', 'Polish Zloty', 'PLN', 0),
('QAR', 'Qatari Riyal', 'QAR', 0),
('RON', 'Romanian Leu', 'RON', 0),
('SAR', 'Saudi Riyal', 'SAR', 0),
('SEK', 'Swedish Krona', 'SEK', 0),
('SGD', 'Singapore Dollar', '$', 0),
('THB', 'Thai Baht', 'THB', 0),
('TRY', 'Turkish Lira', 'TRY', 0),
('USD', 'US Dollar', '$', 0),
('VND', 'Vietnamese Dong', 'VND', 0),
('ZAR', 'South African Rand', 'R', 0);
